### ISSUE TITLE
how to use react-context-menu component?

### ISSUE THREAD

**Issue by cnyzgkn** [amurp/react-context-menu#1]
could the author give detailed steps of using react-context-menu component? or an example?

1. Shall I put ContextMenu.js to my own folder instead of keep it in node_modules folder?

2. if I type "import ContextMenu from 'ContextMenu';" directly, it said "Module not found: Error: Cannot resolve module 'ContextMenu'".

3. I tried to use gulp to convert ContextMenu.js to ES5 style and it showed:
events.js:141
      throw er; // Unhandled 'error' event
      ^

I am quite new in reactJS. Could anyone help me?

**Comment by cnyzgkn** [comment]
Another question is: where can I find wheel.svg and trash.svg?
Thank you

**Comment by amurp** [comment]
Hey @cnyzgkn,

1. It's up to you. Installing via npm and keeping it in node_modules would be the simpler option.

2. This project hasn't been maintained in a while. The readme has now been updated to reflect how you should import ContextMenu once installed through npm:

`import ContextMenu from 'react-context-menu';`

3. I'm not sure what the problem is there but it seems related to your environment and not this component in particular.

For the last question, those svgs were only serving as an example - you can import any svg files you want, but they are not required.

Hope that helps!
